export const ActionTypes = {
    SET_CLASS: "SET_CLASS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    SET_PROFILE: "SET_PROFILE",
    SET_ANNOUNCEMENTS: 'SET_ANNOUNCEMENTS',
    SET_TODOS: 'SET_TODOS'
};
